export const NavLinks = [
    {
        id:1,
        path:'/',
        title:'Home'
    },
    {
        id:2,
        path:'/pricing',
        title:'Pricing'
    },
    {
        id:3,
        path:'/movies',
        title:'Movies'
    },
    {
        id:4,
        path:'/series',
        title:'Series'
    },
    {
        id:5,
        path:'/collection',
        title:'Collection'
    },
    {
        id:6,
        path:'/faq',
        title:'FAQ'
    }
]